jobs:
- job: WindowsVS15
  timeoutInMinutes: 360
  displayName: Windows VS15
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'
        CMakeGenerator: '-G "Visual Studio 15 2017 Win64"'
        MSBuildVersion: '15.0'
        ArchiveNoLibs: 'mlpack-windows-vs15-no-libs.zip'
        ArchiveLibs: 'mlpack-windows-vs15.zip'
        ArchiveTests: 'mlpack_test-vs15.xml'

  steps:
  - template: windows-steps.yaml

- job: WindowsVS16
  timeoutInMinutes: 360
  displayName: Windows VS16
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'
        CMakeGenerator: '-G "Visual Studio 16 2019"'
        MSBuildVersion: '16.0'
        ArchiveNoLibs: 'mlpack-windows-vs16-no-libs.zip'
        ArchiveLibs: 'mlpack-windows-vs16.zip'
        ArchiveTests: 'mlpack_test-vs16.xml'

  steps:
  - template: windows-steps.yaml
